# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftUIAuroraAmplifyTutorial' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # ignore all warnings from all pods
  inhibit_all_warnings!
  
  # Pods for SwiftUIAuroraAmplifyTutorial
  pod 'AWSAppSync'
  pod 'AWSMobileClient', '~> 2.12.1'      # Required dependency
  pod 'amplify-tools'
  pod 'Amplify'
  # pod 'AWSPluginsCore'
  # pod 'AmplifyPlugins/AWSAPIPlugin'
end
