# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftUIAuroraAmplifyTutorial' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # ignore all warnings from all pods
  inhibit_all_warnings!
  
  # Pods for SwiftUIAuroraAmplifyTutorial
  pod 'AWSAppSync'
  pod 'AWSMobileClient', '~> 2.12.1'      # Required dependency
  pod 'amplify-tools'
  pod 'Amplify'
  # pod 'AWSPluginsCore'
  # pod 'AmplifyPlugins/AWSAPIPlugin'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = "YES"
      end
  end
end


